apiVersion: observability.observability.example.com/v1alpha1
kind: Test
metadata:
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/instance: test-sample
    app.kubernetes.io/part-of: 01-operator-sdk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: 01-operator-sdk
  name: test-sample
spec:
  # TODO(user): Add fields here
